services:
  psql:
    image: postgres:14-alpine3.20
    environment:
      POSTGRES_DB: translation
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5444:5432

  translation-service:
    image: translation-service
    build:
      context: .
    ports: [ 8080:8080 ]
    entrypoint: [ "/wait-for.sh", "psql:5432", "--", "/start.sh" ]
    command: [ "java", "-jar", "/app.jar" ]
    depends_on: [ "psql" ]