server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5444/translation'
    username: root
    password: root
    driver-class-name: 'org.postgresql.Driver'

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

rapidapi:
  key: тут key от Rapid
  baseUrl: "https://google-translator9.p.rapidapi.com/v2"
  languageUrl: "https://google-translator9.p.rapidapi.com/v2/languages"